### ISSUE TITLE
Bu ne salak bişey ya

### ISSUE THREAD

**Issue by taumata666** [sudis/ticket-bot#1]
çıldırıcam bot çalayım dedim bu ne lanet bişey lanet olsun sana ya allah damn you kardeşim çalışmıyor token giriyorum v12 yükle diyor discord.js-v12 yüklüyorum haal diror ki throw error bilmem ne mysql kullanmışsın burda bu ne lan bu ne dalga mı geçiriyorsun benimle **aptal karı**?

**Comment by sudis** [comment]
Ok boomer.
